### ISSUE TITLE
gff-ls-files-command

### ISSUE THREAD

**Issue by myimages** [marktriggs/git-find-file.el#1]
Hi, thank you for the package , I like the simplicity and matching algorithm 👍 

I have a number of files that I don't commit to git  ( todo , snippets , notes , wip.txt  ) , or files that still wip and not ready to be committed yet  so I would like to change the command to the following.

```elisp
(setq gff-ls-files-command "find * -type -f")
```

but unfortunately I am getting 

` unknown primary or operator` from within emacs.

another variant of the command that works is 

```elisp
(setq gff-ls-files-command "find  *")
```

but I am getting duplicated results, ones with full path , and the others are relative to .git directory of the project.

the duplicates are returned with double slashes (with the full path) starting from root project.

example
```
vendor/git-find-file.el/git-find-file.el
/Users/apple/.emacs.d//vendor/git-find-file.el/git-find-file.el
```

**Comment by marktriggs** [comment]
Hi @myimages,

I wonder if you could use:

    (setq gff-ls-files-command "git ls-files --others --cached")

which I think would show both committed and uncommitted files.  Any luck with that?

Cheers,
Mark

**Comment by myimages** [comment]
@marktriggs  thank you , did the trick for me.

**Comment by marktriggs** [comment]
Cool!  Glad to hear it :)
